### ISSUE TITLE
Release 0.3.0.1.0

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/rvinecopulib#119]
- [x] seed
- [x] refactor rvine structures
- [x] num_threads for vinecop pdf/cdf/etc
- [x] improve doc (#116)
- [x] Bugs in vine class (#128)
- [x] Bug in vinecop class (#129)
- [x] `keep_data = FALSE`

**Comment by tnagler** [comment]
Shouldn't that be 0.3.0.1.0?

**Comment by tvatter** [comment]
Yes, but the issue was more about listing what's left to do.

**Comment by tnagler** [comment]
Seed should be fine, since we're calling `inverse_rosenblatt_cpp()` on numbers generated by `runif()`.
