### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/rvinecopulib#121]
We have an issue with tll families:

```
rm(list = ls())
library(kdecopula)
library(rvinecopulib)

n <- 1e3
u <- matrix(runif(2*n), n, 2)

methods <- list(
    rvcl = function(x) 
        bicop(x, family_set = "tll", nonpar_method = "quadratic"),
    kdec = function(x) kdecop(x, method = "TLL2"))

sampling <- list(rbicop, rkdecop)

mapply(function(f, s) {
    t_fit <- system.time(fit <- f(u))[3]
    t_sim <- system.time(sim <- s(n, fit))[3]
    res <- c(t_fit, t_sim)
    names(res) <- c("fit [s]", "sim [s]")
    res
    }, methods, sampling)
```
<img width="197" alt="screen shot 2018-06-14 at 15 37 23" src="https://user-images.githubusercontent.com/5273142/41434173-dbf9e62e-6fe8-11e8-9439-bbd5cb28feff.png">

**Comment by tnagler** [comment]
Yeah that's more of a vinecopulib issue, I close this one.

**Comment by tvatter** [comment]
For the posterity, using the new code:

<img width="180" alt="screen shot 2018-07-05 at 14 46 41" src="https://user-images.githubusercontent.com/5273142/42341806-4f9001a2-8062-11e8-99b3-142bb504ffa9.png">

**Comment by tnagler** [comment]
That's amazing, thanks!

**Comment by tnagler** [comment]
Just to show off
================

``` r
library(kdecopula)
library(rvinecopulib)
library(microbenchmark)

u <- rbicop(500, "clay", 0, 3)

microbenchmark(
    rvcl <- bicop(u, family = "nonpar"),
    kdec <- kdecop(u, method = "TLL2"),
    times = 20
)
```

    ## Unit: milliseconds
    ##                                 expr       min        lq      mean
    ##  rvcl <- bicop(u, family = "nonpar")  36.00876  36.51517  36.81121
    ##   kdec <- kdecop(u, method = "TLL2") 117.17961 118.42830 119.56910
    ##     median        uq       max neval
    ##   36.98167  37.07866  37.38334    20
    ##  119.71055 120.26462 123.35464    20

``` r
microbenchmark(dbicop(u, rvcl), dkdecop(u, kdec), times = 20)
```

    ## Unit: microseconds
    ##              expr     min       lq      mean   median       uq     max
    ##   dbicop(u, rvcl)  80.053  82.4375  97.79965  84.0700  86.9135 330.573
    ##  dkdecop(u, kdec) 201.979 206.7905 221.19065 213.9575 228.8290 286.772
    ##  neval
    ##     20
    ##     20

``` r
microbenchmark(pbicop(u, rvcl), pkdecop(u, kdec), times = 20)
```

    ## Unit: milliseconds
    ##              expr        min         lq       mean     median         uq
    ##   pbicop(u, rvcl)   18.29662   18.57537   18.81187   18.67267   19.12771
    ##  pkdecop(u, kdec) 1189.58152 1192.76028 1209.49863 1214.96854 1221.58377
    ##         max neval
    ##    19.61211    20
    ##  1255.62958    20

``` r
microbenchmark(rbicop(1000, rvcl), rkdecop(1000, kdec), times = 20)
```

    ## Unit: milliseconds
    ##                 expr       min        lq      mean   median        uq
    ##   rbicop(1000, rvcl)  42.40462  43.11791  43.60704  43.7228  44.06374
    ##  rkdecop(1000, kdec) 257.49836 260.81038 266.73956 265.0128 268.22618
    ##        max neval
    ##   44.39381    20
    ##  286.94867    20

``` r
microbenchmark::microbenchmark(
    hbicop(u, 1, rvcl),
    hkdecop(u, kdec, 1),
    times = 20
)
```

    ## Unit: microseconds
    ##                 expr      min        lq      mean   median       uq
    ##   hbicop(u, 1, rvcl)  666.250  672.5625  741.1938  735.153  787.322
    ##  hkdecop(u, kdec, 1) 6048.578 6269.4235 7545.1893 7576.352 8569.612
    ##       max neval
    ##   888.885    20
    ##  9668.639    20

``` r
microbenchmark(
    hbicop(u, 1, rvcl, inverse = TRUE),
    hkdecop(u, kdec, 1, inverse = TRUE),
    times = 20
)
```

    ## Unit: milliseconds
    ##                                 expr       min        lq      mean
    ##   hbicop(u, 1, rvcl, inverse = TRUE)  21.59502  21.90407  22.06866
    ##  hkdecop(u, kdec, 1, inverse = TRUE) 122.13182 129.60952 132.42654
    ##     median        uq       max neval
    ##   22.08251  22.20982  22.55913    20
    ##  130.78182 131.34776 154.84610    20
