### ISSUE TITLE
rvine_structure(): storage/input order of struct_array

### ISSUE THREAD

**Issue by tnagler** [vinecopulib/rvinecopulib#160]
``` r
rvine_structure(order = c(5,2,4,1,3), 
                struct_array = list(c(1,4,2,5), c(4,2,5), c(2,5), 5),
                is_natural_order = FALSE)
#> 5-dimensional R-vine structure ('rvine_structure')
#> 5 1 2 3 5
#> 1 2 3 2  
#> 2 3 4    
#> 3 1      
#> 3 
```
does not print a valid R-vine matrix. This is related to some inconsistencies in `rvine_structure()`:
- so far there is no conversion to natural order before storage,
- storage is column-wise, but input of `rvine_structure()` is row-wise and that's not accounted for in all cases.

My proposals:
1. Expect column-wise input to `rvine_structure()` to keep things consistent. I agree that row-wise is more intuitive. But overall it's confusing unless we change storage order to row-wise, too (and that makes the wrappers quite messy).
2. Set up the `rvine_structure()` objects in cpp. We do this for the checks anyway and just need to wrap the object back to an R list.
3. Set `is_natural_order = FALSE` as default. I believe users will rarely want to specify the natural order version.
4. The documentation should contain information on what the "natural order" is exactly.

**Comment by tvatter** [comment]
See #163
