### ISSUE TITLE
Error when running vine()

### ISSUE THREAD

**Issue by mottenbreit** [vinecopulib/rvinecopulib#161]
When running test=vine(df, copula_controls = list(family_set = "nonparametric"))

where df is a dataframe with 3 numerical columns without NA or Inf values gives the following error:

Error in fit_kde1d_cpp(x, bw, xmin, xmax, deg) : 
  Error in function boost::math::pdf(const normal_distribution<double>&, double): Random variate x is nan, but must be finite!

**Comment by tnagler** [comment]
Hi, this is an error related to the [kde1d](https://github.com/tnagler/kde1d) package. I've seen this before when one of the variables is discrete or has an atom. Could you open an issue there, possibly with a reproducible example?
