### ISSUE TITLE
Cannot install version 0.5.2.1.0 on Linux Iridis 5

### ISSUE THREAD

**Issue by sw2d16** [vinecopulib/rvinecopulib#212]
Dear authors,

I have problem installing the latest version of rvinecopulib (version 0.5.2.1.0).  Could you please kindly have a look at the error messages (shown below) for me.  I have installed the essential packages, e.g. RcppEigen, Rcpp, BH, wdm, RcppThread, kde1d.  I am using R version 3.5.2 ("Eggshell Igloo").  

=============================================================
> devtools::install_github("vinecopulib/rvinecopulib@v0.5.2.1.0")
Downloading GitHub repo vinecopulib/rvinecopulib@v0.5.2.1.0
v  checking for file '/tmp/RtmpJo03YK/remotes4b10e252d27c4/vinecopulib-rvinecopulib-cf2cc69/DESCRIPTION' (1.3s)
-  preparing 'rvinecopulib':
v  checking DESCRIPTION meta-information ...
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (339ms)
-  checking for empty or unneeded directories
   Removed empty directory 'rvinecopulib/.github'
-  building 'rvinecopulib_0.5.2.1.0.tar.gz'
   Warning: invalid uid value replaced by that for user 'nobody'

Installing package into '/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5'
(as 'lib' is unspecified)
* installing *source* package 'rvinecopulib' ...
** libs
g++ -std=gnu++11 -I"/local/software/R/3.5.2/lib64/R/include" -DNDEBUG -I../inst/include -pthread -I"/mainfs/local/software/R/3.5.2/lib64/R/library/BH/include" -I"/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I"/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include" -I"/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include" -I"/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/wdm/include" -I"/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/kde1d/include" -I/usr/local/include   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/local/software/R/3.5.2/lib64/R/include" -DNDEBUG -I../inst/include -pthread -I"/mainfs/local/software/R/3.5.2/lib64/R/library/BH/include" -I"/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I"/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include" -I"/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include" -I"/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/wdm/include" -I"/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/kde1d/include" -I/usr/local/include   -fpic  -g -O2 -c vinecopulib-interface.cpp -o vinecopulib-interface.o
In file included from /mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread.h:11:0,
                 from ../inst/include/vinecopulib/misc/tools_interface.hpp:15,
                 from ../inst/include/vinecopulib/bicop/implementation/class.ipp:10,
                 from ../inst/include/vinecopulib/bicop/class.hpp:157,
                 from ../inst/include/vinecopulib.hpp:9,
                 from ../inst/include/vinecopulib-wrappers.hpp:16,
                 from vinecopulib-interface.cpp:1:
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/Thread.hpp: In lambda function:
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/Thread.hpp:42:19: error: parameter packs not expanded with '...':
                 f(args...);
                   ^
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/Thread.hpp:42:19: note:         'args'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/Thread.hpp:42:23: error: expansion pattern 'args' contains no argument packs
                 f(args...);
                       ^
In file included from /mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread.h:13:0,
                 from ../inst/include/vinecopulib/misc/tools_interface.hpp:15,
                 from ../inst/include/vinecopulib/bicop/implementation/class.ipp:10,
                 from ../inst/include/vinecopulib/bicop/class.hpp:157,
                 from ../inst/include/vinecopulib.hpp:9,
                 from ../inst/include/vinecopulib-wrappers.hpp:16,
                 from vinecopulib-interface.cpp:1:
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp: In member function 'void RcppThread::ThreadPool::push(F&&, Args&& ...)':
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:31: error: expected ',' before '...' token
         jobs_.emplace([f, args...] { f(args...); });
                               ^
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:31: error: expected identifier before '...' token
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:34: error: parameter packs not expanded with '...':
         jobs_.emplace([f, args...] { f(args...); });
                                  ^
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:34: note:         'args'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp: In lambda function:
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:44: error: expansion pattern 'args' contains no argument packs
         jobs_.emplace([f, args...] { f(args...); });
                                            ^
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp: In member function 'std::future<decltype (f(args ...))> RcppThread::ThreadPool::pushReturn(F&&, Args&& ...)':
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:144:54: error: expected ',' before '...' token
     auto job = std::make_shared<jobPackage>([&f, args...] {
                                                      ^
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:144:54: error: expected identifier before '...' token
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:144:57: error: parameter packs not expanded with '...':
     auto job = std::make_shared<jobPackage>([&f, args...] {
                                                         ^
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:144:57: note:         'args'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp: In lambda function:
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:145:22: error: expansion pattern 'args' contains no argument packs
         return f(args...);
                      ^
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp: In instantiation of 'struct RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::Bicop::select(const MatrixXd&, vinecopulib::FitControlsBicop)::__lambda64&; Args = {vinecopulib::Bicop&}]::__lambda56':
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:9:   required from 'void RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::Bicop::select(const MatrixXd&, vinecopulib::FitControlsBicop)::__lambda64&; Args = {vinecopulib::Bicop&}]'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:161:9:   required from 'void RcppThread::ThreadPool::map(F&&, I&&) [with F = vinecopulib::Bicop::select(const MatrixXd&, vinecopulib::FitControlsBicop)::__lambda64&; I = std::vector<vinecopulib::Bicop>&]'
../inst/include/vinecopulib/bicop/implementation/class.ipp:829:37:   required from here
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:27: error: using invalid field 'RcppThread::ThreadPool::push(F&&, Args&& ...)::__lambda56::__args'
         jobs_.emplace([f, args...] { f(args...); });
                           ^
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp: In instantiation of 'struct RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::tools_select::VinecopSelector::add_allowed_edges(vinecopulib::tools_select::VineTree&)::__lambda65&; Args = {long unsigned int&}]::__lambda56':
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:9:   required from 'void RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::tools_select::VinecopSelector::add_allowed_edges(vinecopulib::tools_select::VineTree&)::__lambda65&; Args = {long unsigned int&}]'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:161:9:   required from 'void RcppThread::ThreadPool::map(F&&, I&&) [with F = vinecopulib::tools_select::VinecopSelector::add_allowed_edges(vinecopulib::tools_select::VineTree&)::__lambda65&; I = std::pair<boost::range_detail::integer_iterator<long unsigned int>, boost::range_detail::integer_iterator<long unsigned int> >]'
../inst/include/vinecopulib/vinecop/implementation/tools_select.ipp:401:51:   required from here
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:27: error: using invalid field 'RcppThread::ThreadPool::push(F&&, Args&& ...)::__lambda56::__args'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp: In instantiation of 'struct RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::tools_select::VinecopSelector::select_pair_copulas(vinecopulib::tools_select::VineTree&, const VineTree&)::__lambda66&; Args = {boost::detail::edge_desc_impl<boost::undirected_tag, long unsigned int>&}]::__lambda56':
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:9:   required from 'void RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::tools_select::VinecopSelector::select_pair_copulas(vinecopulib::tools_select::VineTree&, const VineTree&)::__lambda66&; Args = {boost::detail::edge_desc_impl<boost::undirected_tag, long unsigned int>&}]'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:161:9:   required from 'void RcppThread::ThreadPool::map(F&&, I&&) [with F = vinecopulib::tools_select::VinecopSelector::select_pair_copulas(vinecopulib::tools_select::VineTree&, const VineTree&)::__lambda66&; I = std::pair<boost::detail::undirected_edge_iter<std::_List_iterator<boost::list_edge<long unsigned int, boost::property<boost::edge_weight_t, double, vinecopulib::tools_select::EdgeProperties> > >, boost::detail::edge_desc_impl<boost::undirected_tag, long unsigned int>, long int>, boost::detail::undirected_edge_iter<std::_List_iterator<boost::list_edge<long unsigned int, boost::property<boost::edge_weight_t, double, vinecopulib::tools_select::EdgeProperties> > >, boost::detail::edge_desc_impl<boost::undirected_tag, long unsigned int>, long int> >]'
../inst/include/vinecopulib/vinecop/implementation/tools_select.ipp:1010:42:   required from here
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:27: error: using invalid field 'RcppThread::ThreadPool::push(F&&, Args&& ...)::__lambda56::__args'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp: In instantiation of 'struct RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::Vinecop::pdf(Eigen::MatrixXd, size_t) const::__lambda67&; Args = {vinecopulib::tools_batch::Batch&}]::__lambda56':
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:9:   required from 'void RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::Vinecop::pdf(Eigen::MatrixXd, size_t) const::__lambda67&; Args = {vinecopulib::tools_batch::Batch&}]'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:161:9:   required from 'void RcppThread::ThreadPool::map(F&&, I&&) [with F = vinecopulib::Vinecop::pdf(Eigen::MatrixXd, size_t) const::__lambda67&; I = std::vector<vinecopulib::tools_batch::Batch>]'
../inst/include/vinecopulib/vinecop/implementation/class.ipp:826:74:   required from here
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:27: error: using invalid field 'RcppThread::ThreadPool::push(F&&, Args&& ...)::__lambda56::__args'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp: In instantiation of 'struct RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::Vinecop::rosenblatt(const MatrixXd&, size_t) const::__lambda68&; Args = {vinecopulib::tools_batch::Batch&}]::__lambda56':
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:9:   required from 'void RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::Vinecop::rosenblatt(const MatrixXd&, size_t) const::__lambda68&; Args = {vinecopulib::tools_batch::Batch&}]'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:161:9:   required from 'void RcppThread::ThreadPool::map(F&&, I&&) [with F = vinecopulib::Vinecop::rosenblatt(const MatrixXd&, size_t) const::__lambda68&; I = std::vector<vinecopulib::tools_batch::Batch>]'
../inst/include/vinecopulib/vinecop/implementation/class.ipp:1079:67:   required from here
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:27: error: using invalid field 'RcppThread::ThreadPool::push(F&&, Args&& ...)::__lambda56::__args'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp: In instantiation of 'struct RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::Vinecop::inverse_rosenblatt(const MatrixXd&, size_t) const::__lambda69&; Args = {vinecopulib::tools_batch::Batch&}]::__lambda56':
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:9:   required from 'void RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = vinecopulib::Vinecop::inverse_rosenblatt(const MatrixXd&, size_t) const::__lambda69&; Args = {vinecopulib::tools_batch::Batch&}]'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:161:9:   required from 'void RcppThread::ThreadPool::map(F&&, I&&) [with F = vinecopulib::Vinecop::inverse_rosenblatt(const MatrixXd&, size_t) const::__lambda69&; I = std::vector<vinecopulib::tools_batch::Batch>]'
../inst/include/vinecopulib/vinecop/implementation/class.ipp:1196:67:   required from here
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:27: error: using invalid field 'RcppThread::ThreadPool::push(F&&, Args&& ...)::__lambda56::__args'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp: In instantiation of 'struct RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = fit_margins_cpp(const MatrixXd&, const VectorXi&, const VectorXd&, const VectorXd&, const VectorXd&, const VectorXd&, const VectorXi&, const VectorXd&, size_t)::__lambda84&; ptrdiff_t = long int; size_t = long unsigned int]::__lambda59&; Args = {const RcppThread::Batch&}]::__lambda56':
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:9:   required from 'void RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = fit_margins_cpp(const MatrixXd&, const VectorXi&, const VectorXd&, const VectorXd&, const VectorXd&, const VectorXd&, const VectorXi&, const VectorXd&, size_t)::__lambda84&; ptrdiff_t = long int; size_t = long unsigned int]::__lambda59&; Args = {const RcppThread::Batch&}]'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:199:9:   required from 'void RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = fit_margins_cpp(const MatrixXd&, const VectorXi&, const VectorXd&, const VectorXd&, const VectorXd&, const VectorXd&, const VectorXi&, const VectorXd&, size_t)::__lambda84&; ptrdiff_t = long int; size_t = long unsigned int]'
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/parallelFor.hpp:48:5:   required from 'void RcppThread::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t, size_t) [with F = fit_margins_cpp(const MatrixXd&, const VectorXi&, const VectorXd&, const VectorXd&, const VectorXd&, const VectorXd&, const VectorXi&, const VectorXd&, size_t)::__lambda84; ptrdiff_t = long int; size_t = long unsigned int]'
vinecopulib-interface.cpp:310:38:   required from here
/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/RcppThread/include/RcppThread/ThreadPool.hpp:127:27: error: using invalid field 'RcppThread::ThreadPool::push(F&&, Args&& ...)::__lambda56::__args'
make: *** [vinecopulib-interface.o] Error 1
ERROR: compilation failed for package 'rvinecopulib'
* removing '/mainfs/home/sw2d16/R/x86_64-pc-linux-gnu-library/3.5/rvinecopulib'
Error: Failed to install 'rvinecopulib' from GitHub:
  (converted from warning) installation of package '/tmp/RtmpJo03YK/file4b10e46ca3b1a/rvinecopulib_0.5.2.1.0.tar.gz' had non-zero exit status

=============================================================
Thank you so much in advance for your help.

Suttisak

**Comment by tvatter** [comment]
@sw2d16 it seems like the error is coming from either your compiler not supporting some C++11 stuff or from issues in [RcppThread](https://cran.r-project.org/web/packages/RcppThread/index.html).

Two ideas:

- What compiler are you using? Does it support C++11?
- If the compiler is "recent enough", is there any chance that you could try to install one or two packages that also depend on RcppThread and see if you get the same issue? You could try: dodgr, dtwclust, rayrender, RcppAlgos, RcppBigIntAlgos, treenomial, universalmotif, vinereg...

@tnagler other ideas? The [parameter packs not expanded with '…' error seems something known.](https://stackoverflow.com/questions/33868486/parameter-packs-not-expanded-with)

**Comment by tnagler** [comment]
Seems to be the same problem as in [this](https://github.com/tnagler/RcppThread/issues/13) RcppThread issue. Updating g++ should do the trick.

**Comment by sw2d16** [comment]
Dear Thibault and Thomas,

Thank you so much for your speedy responses.  I have tried installing RcppThread-dependency packages and found them to be failed as well as rvinecopulib.  So I agree with you it was about the compiler.  Since I have no ability to update or alter anything on it (since the platform I am using belongs to the university system), I would contact them and point out this problem.

Would let you know how it goes.  Thank you so so much :)

Suttisak

**Comment by tvatter** [comment]
Yeah, I figured that Linux Iridis 5 must be a computing cluster :) Hopefully the admins will be able to install a newer version of the C++ compiler, as it seems like the one currently installed isn't fully C++11 compliant.

Is https://www.southampton.ac.uk/isolutions/staff/iridis.page the cluster that you are using?
