### ISSUE TITLE
Automatic Threshold selection without automatic truncation causes error

### ISSUE THREAD

**Issue by mcwachter** [vinecopulib/rvinecopulib#228]
Hello,
I am using your package for my research and I have trouble using the automated threshold selection using the mbicv in the function vinecop.
Setting `threshold = NA` without setting `trunc_lvl=NA` aswell (this mean `trunc_lvl=Inf`) leads to several error messages like, bad_alloc,

invalid permissions 
```
*** caught segfault ***
address 0x14df5c002000, cause 'invalid permissions'
Traceback:
1: vinecop_select_cpp(data = as.matrix(data), structure = structure,     family_set = family_set, par_method = par_method,  nonpar_method = nonpar_method,     mult = mult, selection_criterion = selcrit, weights = weights,     psi0 = psi0, preselect_families = presel, truncation_level = ifelse(is.finite(trunc_lvl),         trunc_lvl, .Machine$integer.max), tree_criterion = tree_crit,     threshold = threshold, select_truncation_level = is.na(trunc_lvl),     select_threshold = is.na(threshold), show_trace = show_trace,     num_threads = cores, var_types = var_types)
2: vinecop(pseudo_obs(dataset), selcrit = "mbicv", threshold = NA,     cores = available.cores())
An irrecoverable exception occurred. R is aborting now ...
```
or memory not mapped (same traceback as above)
```
*** caught segfault ***
address (nil), cause 'memory not mapped'
```
Unfortunately, I was not able to get the systematic behind these three error messages, since the error message differs sometimes even if the code is rerun without any changes. I wrote a little example using normal distributed data to illustrate the problem. The only way I was able to use the automatic threshold selection in this example was by setting `trunc_lvl=NA` aswell. 
     
```
library(rvinecopulib)
library(parallel)

available.cores = function () {
  max(1, detectCores() - 1)
}

set.seed(12)
dataset <- matrix(ncol=10,rnorm(50*10,0,1))

copula = vinecop(pseudo_obs(dataset),
                 threshold = NA,
                 trunc_lvl = NA,    #comment this out for testing
                 show_trace = TRUE,
                 cores=available.cores())
```
Mysteriously, using the data given in https://github.com/mcwachter/rvinecopulib_Issue/blob/main/data.csv `trunc_lvl=NA` is not neccessary. So in general, using `threshold=NA` with `trunc_lvl=Inf` is possible. But for many other datasets I tried, it was the same as in the example with the normal distributed data.

Honestly, I have no clue where this comes from but I looked into the R source Code and noticed that in the `vinecop` function (https://github.com/vinecopulib/rvinecopulib/blob/master/R/vinecop.R) does not check in line 167 whether `threshold` is `NA`. Contrary, in line 161 `truncation_lvl` is set to the maximum Integer if `trunc_lvl` is `NA`, since `is.finite(NA)` is `FALSE`. So for `trunc_lvl` `NA` is not passed to C++ but for `threshold` this is the case. Maybe this causes the described behaviour.

Many thanks in advance!

**Comment by tnagler** [comment]
Thanks for the detailed report and example!

That was indeed a hard bug to track down. In your specific example at least, the problem is that data is independent. For such cases, there was an error in the logic. The algorithm threw away the fitted model after the first iteration of threshold search, but then stopped without any model at hand. #229 is supposed fixes that. You can install with `devtools::install_github("vinecopulib/rvinecopulib@fix-sparse-indep")` and check if that solves your problems?

**Comment by mcwachter** [comment]
Thank you for that quick support. 
This seems to work, even with my non-independent data.
