### ISSUE TITLE
plot font size selection

### ISSUE THREAD

**Issue by TY-Cheng** [vinecopulib/rvinecopulib#236]
Thank you so much for your excellent work.

When charting for multiple variables the edge label looks over-crowded and would like to shrink them. not yet doable by par(cex).
<img width="335" alt="image" src="https://user-images.githubusercontent.com/14033617/109409878-3b015180-79d1-11eb-9b8b-4e2bfe1b14e0.png">

BTW, Is the output from plot function of ggraph class? 
Wondering if we can have more compatible output like of igraph or NetworkX then we can modify the visualisation (layout & label font & edge color/line types/thickness) by ourselves. 

Thanks a lot!

**Comment by tnagler** [comment]
Sorry for the late response. The plot environment actually contains the corresponding `igraph` object, but I admit that this is not obvious. 

Here's how to do it:
``` r
# generate random model
u <- matrix(runif(200 * 5), 200, 5)
colnames(u) <- paste0("var_", 1:5)
vc <- vinecop(u, family = "clayton")

# extract igraph object from plot environment
plt <- plot(vc, edge_labels = "family_tau")
igr_obj <- get("g", plt$plot_env)[[1]]

igr_obj
#> IGRAPH f9c5744 UN-- 5 4 -- 
#> + attr: name (v/c), name (e/c)
#> + edges from f9c5744 (vertex names):
#> [1] 4--1 2--1 1--3 3--5

igraph::E(igr_obj)$name
#> [1] "clayton(0.05)"  "clayton(-0.06)" "clayton(-0.01)" "clayton(0.01)" 

igraph::V(igr_obj)$name
#> [1] "4" "2" "1" "3" "5"
```

I will add this to the documentation. Thanks!
