### ISSUE TITLE
no function to create random generator like Mvdc in Copula

### ISSUE THREAD

**Issue by longbiao1993** [vinecopulib/rvinecopulib#240]
Thank you so much for your excellent work!
Rvinecopulib needs a function like Mvdc in Copula, which helps us compare the simulated result and origin data.

**Comment by tvatter** [comment]
https://vinecopulib.github.io/rvinecopulib/reference/vinecop_methods.html

**Comment by longbiao1993** [comment]
Thank you for your speedly response, rbicop is  different with Mvdc, rbicop create the matrix  values ranging from 0 to 1. Mvdc can create  the matrix which's range is defined by some parameters from the normal or gamma distibution.
