### ISSUE TITLE
kernel copula 

### ISSUE THREAD

**Issue by laten21** [vinecopulib/rvinecopulib#249]
Hi, is there a package provides all the kernel copula methods with more than two variables such as the methods in kdecop package?
I found the rvinecoplib package but it just include the transformation and local kernels. where can I find the other methods please

Thanks

**Comment by tnagler** [comment]
https://tnagler.github.io/kdevine/reference/kdevinecop.html

**Comment by laten21** [comment]
That's great, thank you so much.
