### ISSUE TITLE
Bug in compute_pseudo_obs for discrete variables

### ISSUE THREAD

**Issue by rplzzz** [vinecopulib/rvinecopulib#257]
In `compute_pseudo_obs`, when we are presented with discrete variables we have to evaluate the left-limits of the univariate distribution functions, which is done here: 

https://github.com/vinecopulib/rvinecopulib/blob/0c9ba0dfcaa5c0143af1591407b2e26689720a4a/R/vine.R#L175-L180

In line 178, the factor must be created with the `ordered = TRUE` option because this factor will be passed to `pkde1d`, and the kde1d functions give incorrect answers for factors that are not ordered.

NB: I found this particular instance because it was causing me problems, but I haven't checked to see if there are other places where factors are being created for discrete variables, nor, if so, whether they are being created as ordered factors.

**Comment by tnagler** [comment]
Fixed by 1dac049eb21953569fb49f062c50ed00c7d527dc, thanks!
