### ISSUE TITLE
difference between vine and vinecop

### ISSUE THREAD

**Issue by whyzjuhit** [vinecopulib/rvinecopulib#261]
Hi,Thomas. Is there any difference between vine and vinecop?  Which one shloud I choose to fit a copula model?

**Comment by tnagler** [comment]
Yes, vine fits marginal distributions plus copula model. vinecop only fits the copula, so you have to do the marginal modeling yourself.

**Comment by whyzjuhit** [comment]
> Yes, vine fits marginal distributions plus copula model. vinecop only fits the copula, so you have to do the marginal modeling yourself.

Thanks a lot.
