### ISSUE TITLE
Distribution logis not handled

### ISSUE THREAD

**Issue by njaalf** [vinecopulib/rvinecopulib#274]
Hi, I have problems with the logistic marginal (part of stats::Distributions). 

This code runs fine:
margins <- list(list(distr="norm"), list(distr="norm"))
bicop <- bicop_dist("bb1", 90, c(3, 2))
pcs <- list(list(bicop)) 
vv <- vine_dist(margins, pcs, dvine_structure(1:2) )

However: 
margins <- list(list(distr="logis"), list(distr="norm"))
vv <- vine_dist(margins, pcs, dvine_structure(1:2) )

yields: Error in sum(sapply(margins, get_npars_distr)) : 
  invalid 'type' (list) of argument

**Comment by tnagler** [comment]
Fixed in #275, thanks!
