### ISSUE TITLE
exclude vinecopulib code from this repo

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/rvinecopulib#4]
see previous discussion here: https://github.com/tnagler/vinecopulib-R/issues/2

**Comment by tnagler** [comment]
The problem with having it fully automatic is that the R package may fail to work when we haven't adapted the R package to changes in the C++ library. Hence, we must allow having two different C++ versions in vinecopulib and rvinecopulib.

The current "solution" is the bash script  [`/src/update_vinecopulib.sh`](https://github.com/vinecopulib/rvinecopulib/blob/master/src/update_vinecopulib.sh) which pulls from vinecopulib master and moves the files to the right location. Maybe a better long-term solution is to have a cron-job doing this and pushing to a dedicated branch.

**Comment by slayoo** [comment]
what about pulling a precise release (or revision) - the Python bindings now pull the "Dev" branch by default on Travis and AppVeyor builds for example

**Comment by tnagler** [comment]
I'm afraid CRAN doesn't allow running git commands in the installation process (not even bash scripts).

**Comment by slayoo** [comment]
for the record, here's an example of how a similar situation is handled in the C++ ndarray package which requires Boost.NumPy to be build: https://github.com/ndarray/ndarray

In short, cloning is done by:
```
git clone git@github.com:ndarray/ndarray.git
cd ndarray
git submodule update --init --recursive
```

**Comment by slayoo** [comment]
(but of course it does not apply if running git commands is not an option...)

**Comment by tvatter** [comment]
I'm closing for now, as the current solution seems here to stay.
